/* ============================================================
   आज़ादी Quiz — 150 verified questions on India's independence
   struggle, organised by difficulty. Every fact here traces to
   the same sources used across the site (Wikipedia / Wikimedia
   Commons); each question links to its source for further reading.
   ============================================================ */

const QUIZ_WIKI = (title) => `https://en.wikipedia.org/wiki/${title}`;

const QUIZ_QUESTIONS = [

  /* ---------------- EASY (52) ---------------- */
  { difficulty: "easy", q: "In which year did India gain independence from British rule?",
    options: ["1942", "1947", "1950", "1930"], correct: 1,
    explanation: "India became independent at midnight on 15 August 1947, ending nearly two centuries of British control.",
    link: QUIZ_WIKI("Indian_Independence_Day") },
  { difficulty: "easy", q: "Who is known as the “Father of the Nation” in India?",
    options: ["Jawaharlal Nehru", "Subhas Chandra Bose", "Mahatma Gandhi", "Sardar Patel"], correct: 2,
    explanation: "Mahatma Gandhi led the independence movement through non-violent civil disobedience and is widely honoured as the Father of the Nation.",
    link: QUIZ_WIKI("Mahatma_Gandhi") },
  { difficulty: "easy", q: "Who was independent India's first Prime Minister?",
    options: ["Jawaharlal Nehru", "Sardar Patel", "Rajendra Prasad", "Mahatma Gandhi"], correct: 0,
    explanation: "Jawaharlal Nehru served as India's first Prime Minister from 1947 until his death in 1964.",
    link: QUIZ_WIKI("Jawaharlal_Nehru") },
  { difficulty: "easy", q: "On what date is Indian Independence Day celebrated?",
    options: ["26 January", "2 October", "15 August", "15 November"], correct: 2,
    explanation: "15 August marks the day in 1947 that India became independent from British rule.",
    link: QUIZ_WIKI("Indian_Independence_Day") },
  { difficulty: "easy", q: "How many spokes does the Ashoka Chakra on the Indian flag have?",
    options: ["16", "20", "24", "32"], correct: 2,
    explanation: "The Ashoka Chakra at the centre of the Indian flag has 24 spokes.",
    link: QUIZ_WIKI("Flag_of_India") },
  { difficulty: "easy", q: "Who led the famous Salt March to Dandi in 1930?",
    options: ["Jawaharlal Nehru", "Mahatma Gandhi", "Sardar Patel", "Subhas Chandra Bose"], correct: 1,
    explanation: "Gandhi walked 240 miles to the coastal village of Dandi to make salt from the sea, defying the British salt tax.",
    link: QUIZ_WIKI("Salt_March") },
  { difficulty: "easy", q: "What was the name of the movement Gandhi launched in 1942 with the call “Do or Die”?",
    options: ["Non-Cooperation Movement", "Quit India Movement", "Swadeshi Movement", "Civil Disobedience Movement"], correct: 1,
    explanation: "The Quit India Movement, launched on 8 August 1942, was the largest civil uprising since 1857.",
    link: QUIZ_WIKI("Quit_India_Movement") },
  { difficulty: "easy", q: "Who founded the Indian National Army (INA)?",
    options: ["Bhagat Singh", "Subhas Chandra Bose", "Chandrashekhar Azad", "Jawaharlal Nehru"], correct: 1,
    explanation: "Subhas Chandra Bose formed the Indian National Army to fight for independence from outside British India's borders.",
    link: QUIZ_WIKI("Subhas_Chandra_Bose") },
  { difficulty: "easy", q: "What is Subhas Chandra Bose's popular title?",
    options: ["Lokmanya", "Sardar", "Netaji", "Maulana"], correct: 2,
    explanation: "“Netaji”, meaning respected leader, is the honorific most associated with Subhas Chandra Bose.",
    link: QUIZ_WIKI("Subhas_Chandra_Bose") },
  { difficulty: "easy", q: "In which year was the Indian National Congress founded?",
    options: ["1857", "1885", "1905", "1919"], correct: 1,
    explanation: "The Indian National Congress was founded in 1885 and became the organised political voice of the independence movement.",
    link: QUIZ_WIKI("Indian_National_Congress") },
  { difficulty: "easy", q: "In which city was the Indian National Congress founded?",
    options: ["Delhi", "Calcutta", "Bombay", "Madras"], correct: 2,
    explanation: "The first session of the Indian National Congress met in Bombay in December 1885.",
    link: QUIZ_WIKI("Indian_National_Congress") },
  { difficulty: "easy", q: "Which European trading company gradually took political control of India from the 1600s onward?",
    options: ["The Dutch East India Company", "The East India Company", "The Portuguese Trading Company", "The British Crown"], correct: 1,
    explanation: "The (British) East India Company, chartered in 1600, evolved from a trading concern into India's ruling power.",
    link: QUIZ_WIKI("East_India_Company") },
  { difficulty: "easy", q: "In which year did the East India Company receive its royal charter?",
    options: ["1600", "1707", "1757", "1858"], correct: 0,
    explanation: "Queen Elizabeth I granted the East India Company its royal charter on 31 December 1600.",
    link: QUIZ_WIKI("East_India_Company") },
  { difficulty: "easy", q: "In which city did the Jallianwala Bagh massacre take place in 1919?",
    options: ["Lahore", "Amritsar", "Delhi", "Lucknow"], correct: 1,
    explanation: "British troops fired on an unarmed crowd in a walled garden in Amritsar on 13 April 1919.",
    link: QUIZ_WIKI("Jallianwala_Bagh_massacre") },
  { difficulty: "easy", q: "What was Bhagat Singh's famous rallying slogan?",
    options: ["Jai Hind", "Inquilab Zindabad", "Vande Mataram", "Satyameva Jayate"], correct: 1,
    explanation: "“Inquilab Zindabad”, meaning “Long live the revolution”, is the slogan Bhagat Singh made immortal.",
    link: QUIZ_WIKI("Bhagat_Singh") },
  { difficulty: "easy", q: "At what age was Bhagat Singh executed?",
    options: ["19", "21", "23", "27"], correct: 2,
    explanation: "Bhagat Singh was hanged in Lahore on 23 March 1931 at the age of 23.",
    link: QUIZ_WIKI("Bhagat_Singh") },
  { difficulty: "easy", q: "Who is remembered as the “Iron Man of India” for unifying the princely states?",
    options: ["Sardar Vallabhbhai Patel", "Jawaharlal Nehru", "Rajendra Prasad", "C. Rajagopalachari"], correct: 0,
    explanation: "Sardar Vallabhbhai Patel, India's first Deputy Prime Minister, led the political integration of the princely states.",
    link: QUIZ_WIKI("Vallabhbhai_Patel") },
  { difficulty: "easy", q: "Who is known as the “Nightingale of India”?",
    options: ["Sarojini Naidu", "Annie Besant", "Bhikaiji Cama", "Rani Lakshmibai"], correct: 0,
    explanation: "Poet and orator Sarojini Naidu earned the epithet for verse steeped in Indian imagery.",
    link: QUIZ_WIKI("Sarojini_Naidu") },
  { difficulty: "easy", q: "Which warrior queen fought the British during the 1857 uprising?",
    options: ["Rani Lakshmibai of Jhansi", "Sarojini Naidu", "Bhikaiji Cama", "Begum Hazrat Mahal"], correct: 0,
    explanation: "Rani Lakshmibai led her own troops into battle rather than surrender her state, and died fighting at Gwalior in 1858.",
    link: QUIZ_WIKI("Rani_of_Jhansi") },
  { difficulty: "easy", q: "Who chaired the Drafting Committee of the Indian Constitution?",
    options: ["Jawaharlal Nehru", "Dr. B. R. Ambedkar", "Rajendra Prasad", "Sardar Patel"], correct: 1,
    explanation: "Dr. B. R. Ambedkar was the chief architect of India's Constitution as chairman of its Drafting Committee.",
    link: QUIZ_WIKI("B._R._Ambedkar") },
  { difficulty: "easy", q: "Who delivered the “Tryst with Destiny” speech on the eve of independence?",
    options: ["Mahatma Gandhi", "Jawaharlal Nehru", "Sardar Patel", "Rajendra Prasad"], correct: 1,
    explanation: "Nehru addressed the Constituent Assembly with this speech just before midnight on 14 August 1947.",
    link: QUIZ_WIKI("Jawaharlal_Nehru") },
  { difficulty: "easy", q: "At what time of day did India officially become independent on 15 August 1947?",
    options: ["Dawn", "Noon", "Midnight", "Dusk"], correct: 2,
    explanation: "India's independence took effect at the stroke of midnight between 14 and 15 August 1947.",
    link: QUIZ_WIKI("Indian_Independence_Day") },
  { difficulty: "easy", q: "Into which two countries was British India partitioned in 1947?",
    options: ["India and Bangladesh", "India and Pakistan", "India and Burma", "India and Ceylon"], correct: 1,
    explanation: "The Partition of India in 1947 created the independent dominions of India and Pakistan.",
    link: QUIZ_WIKI("Partition_of_India") },
  { difficulty: "easy", q: "Which sepoy's revolt at Barrackpore in 1857 is often cited as the spark of the uprising?",
    options: ["Mangal Pandey", "Bahadur Shah Zafar", "Nana Sahib", "Tantia Tope"], correct: 0,
    explanation: "Mangal Pandey's revolt on 29 March 1857 is widely regarded as the spark that lit the wider uprising.",
    link: QUIZ_WIKI("Mangal_Pandey") },
  { difficulty: "easy", q: "What British tax did Gandhi's Salt March defy?",
    options: ["The income tax", "The land tax", "The salt tax", "The customs tax"], correct: 2,
    explanation: "Gandhi marched to the sea to make salt himself, in open defiance of the British monopoly and tax on salt.",
    link: QUIZ_WIKI("Salt_March") },
  { difficulty: "easy", q: "Who wrote India's national anthem, “Jana Gana Mana”?",
    options: ["Bankim Chandra Chattopadhyay", "Rabindranath Tagore", "Sarojini Naidu", "Muhammad Iqbal"], correct: 1,
    explanation: "Rabindranath Tagore wrote and composed “Jana Gana Mana”, adopted as India's national anthem.",
    link: QUIZ_WIKI("Jana_Gana_Mana") },
  { difficulty: "easy", q: "Who composed “Vande Mataram”, India's national song?",
    options: ["Rabindranath Tagore", "Bankim Chandra Chattopadhyay", "Iqbal", "Subramania Bharati"], correct: 1,
    explanation: "Bankim Chandra Chattopadhyay wrote “Vande Mataram”, which became a rallying cry of the independence movement.",
    link: QUIZ_WIKI("Vande_Mataram") },
  { difficulty: "easy", q: "In which year did the Jallianwala Bagh massacre take place?",
    options: ["1909", "1919", "1929", "1942"], correct: 1,
    explanation: "The massacre took place on 13 April 1919 in Amritsar.",
    link: QUIZ_WIKI("Jallianwala_Bagh_massacre") },
  { difficulty: "easy", q: "Which British officer ordered troops to fire on the crowd at Jallianwala Bagh?",
    options: ["General Reginald Dyer", "Lord Curzon", "Lord Mountbatten", "Sir Michael O'Dwyer"], correct: 0,
    explanation: "Brigadier-General Reginald Dyer ordered the troops to open fire without warning.",
    link: QUIZ_WIKI("Jallianwala_Bagh_massacre") },
  { difficulty: "easy", q: "What colour is at the top of the Indian national flag?",
    options: ["Green", "White", "Saffron", "Blue"], correct: 2,
    explanation: "The Indian flag has saffron at the top, white in the middle, and green at the bottom.",
    link: QUIZ_WIKI("Flag_of_India") },
  { difficulty: "easy", q: "What colour is at the bottom of the Indian national flag?",
    options: ["Saffron", "White", "Green", "Navy blue"], correct: 2,
    explanation: "Green forms the bottom band of the Indian tricolour.",
    link: QUIZ_WIKI("Flag_of_India") },
  { difficulty: "easy", q: "What symbol sits at the centre of the Indian flag?",
    options: ["A lotus", "The Ashoka Chakra", "A star", "A sun"], correct: 1,
    explanation: "The navy-blue Ashoka Chakra, a 24-spoke wheel, sits at the centre of the white band.",
    link: QUIZ_WIKI("Flag_of_India") },
  { difficulty: "easy", q: "Who was India's first Deputy Prime Minister?",
    options: ["Sardar Vallabhbhai Patel", "Jawaharlal Nehru", "Rajendra Prasad", "Maulana Azad"], correct: 0,
    explanation: "Sardar Patel served as India's first Deputy Prime Minister and Home Minister.",
    link: QUIZ_WIKI("Vallabhbhai_Patel") },
  { difficulty: "easy", q: "Who chaired India's Constituent Assembly?",
    options: ["Jawaharlal Nehru", "Dr. Rajendra Prasad", "Dr. B. R. Ambedkar", "Sardar Patel"], correct: 1,
    explanation: "Dr. Rajendra Prasad presided over the Constituent Assembly from 1946 to 1950.",
    link: QUIZ_WIKI("Rajendra_Prasad") },
  { difficulty: "easy", q: "Who became independent India's first President?",
    options: ["Jawaharlal Nehru", "C. Rajagopalachari", "Dr. Rajendra Prasad", "Sardar Patel"], correct: 2,
    explanation: "Dr. Rajendra Prasad became the first President of the Republic of India in 1950.",
    link: QUIZ_WIKI("Rajendra_Prasad") },

    { difficulty: "easy", q: "At which port did the first English East India Company ship arrive in 1608, marking the start of British trade in India?",
    options: ["Bombay", "Surat", "Calcutta", "Madras"], correct: 1,
    explanation: "The Company ship Hector, commanded by William Hawkins, anchored at Surat in August 1608 — the Company's first foothold on Indian soil.",
    link: QUIZ_WIKI("William_Hawkins_(fl._c._1600)") },
  { difficulty: "easy", q: "In which Indian state was Mahatma Gandhi born?",
    options: ["Maharashtra", "Gujarat", "Rajasthan", "Punjab"], correct: 1,
    explanation: "Gandhi was born in the coastal town of Porbandar, Gujarat, in 1869.",
    link: QUIZ_WIKI("Mahatma_Gandhi") },
  { difficulty: "easy", q: "What was Gandhi's first satyagraha campaign in India, fought on behalf of indigo farmers?",
    options: ["Kheda Satyagraha", "Bardoli Satyagraha", "Champaran Satyagraha", "Dharasana Satyagraha"], correct: 2,
    explanation: "Gandhi's 1917 Champaran Satyagraha, defending indigo farmers against forced cultivation, was his first act of civil disobedience on Indian soil.",
    link: QUIZ_WIKI("Champaran_Satyagraha") },
  { difficulty: "easy", q: "Which title did the women of Bardoli give Vallabhbhai Patel after his 1928 tax-revolt campaign?",
    options: ["Netaji", "Sardar", "Lokmanya", "Mahatma"], correct: 1,
    explanation: "After leading the Bardoli Satyagraha, Patel was given the title 'Sardar', meaning chief, which stayed with him for life.",
    link: QUIZ_WIKI("Vallabhbhai_Patel") },
  { difficulty: "easy", q: "What is the name of Gandhi's ashram on the Sabarmati river, from which he set out on the Salt March?",
    options: ["Sevagram Ashram", "Sabarmati Ashram", "Aga Khan Palace", "Wardha Ashram"], correct: 1,
    explanation: "Gandhi departed from Sabarmati Ashram in Ahmedabad on 12 March 1930 to march to the sea at Dandi.",
    link: QUIZ_WIKI("Sabarmati_Ashram") },
  { difficulty: "easy", q: "Who was the last Mughal emperor, proclaimed leader by rebel sepoys during the 1857 uprising?",
    options: ["Bahadur Shah Zafar", "Shah Alam II", "Akbar II", "Humayun"], correct: 0,
    explanation: "Bahadur Shah Zafar, an elderly poet with no real army, was proclaimed the rebellion's symbolic leader in Delhi in 1857.",
    link: QUIZ_WIKI("Bahadur_Shah_Zafar") },
  { difficulty: "easy", q: "In which year did the Constituent Assembly formally adopt the Constitution of India?",
    options: ["1947", "1948", "1949", "1950"], correct: 2,
    explanation: "The Constitution was adopted on 26 November 1949, though it came into force a little over a month later, on 26 January 1950.",
    link: QUIZ_WIKI("Constitution_of_India") },
  { difficulty: "easy", q: "Who served as India's first Governor-General after independence in 1947?",
    options: ["C. Rajagopalachari", "Lord Mountbatten", "Lord Wavell", "Rajendra Prasad"], correct: 1,
    explanation: "Lord Mountbatten, the last Viceroy, stayed on as independent India's first Governor-General until 1948.",
    link: QUIZ_WIKI("Louis_Mountbatten,_1st_Earl_Mountbatten_of_Burma") },
  { difficulty: "easy", q: "Which Indian city served as the capital of British India before it moved to Delhi in 1911?",
    options: ["Bombay", "Madras", "Calcutta", "Lucknow"], correct: 2,
    explanation: "Calcutta was the capital of British India until King George V announced the move to Delhi at the 1911 Delhi Durbar.",
    link: QUIZ_WIKI("Delhi_Durbar") },
  { difficulty: "easy", q: "Who is remembered as the 'Grand Old Man of India' for his pioneering role in early Indian nationalist politics?",
    options: ["Dadabhai Naoroji", "Gopal Krishna Gokhale", "Surendranath Banerjee", "W. C. Banerjee"], correct: 0,
    explanation: "Dadabhai Naoroji, a founding figure of the Indian National Congress and the first Indian elected to the British Parliament, earned the title 'Grand Old Man of India'.",
    link: QUIZ_WIKI("Dadabhai_Naoroji") },
  { difficulty: "easy", q: "What is the national emblem of India, adopted in 1950, based on?",
    options: ["The peacock throne", "The Lion Capital of Ashoka", "The Konark wheel", "The Taj Mahal"], correct: 1,
    explanation: "India's State Emblem is an adaptation of the Lion Capital of Ashoka, a 3rd-century BCE sculpture originally erected at Sarnath.",
    link: QUIZ_WIKI("State_Emblem_of_India") },
  { difficulty: "easy", q: "Which day of the year is celebrated as India's Republic Day?",
    options: ["15 August", "2 October", "26 January", "26 November"], correct: 2,
    explanation: "Republic Day, 26 January, marks the date the Constitution of India came into force in 1950.",
    link: QUIZ_WIKI("Republic_Day_(India)") },
  { difficulty: "easy", q: "Who wrote the book 'Hind Swaraj', outlining his vision of self-rule and non-violent resistance?",
    options: ["Jawaharlal Nehru", "Mahatma Gandhi", "Bal Gangadhar Tilak", "Subhas Chandra Bose"], correct: 1,
    explanation: "Gandhi wrote 'Hind Swaraj' in 1909, laying out his early philosophy of Indian self-rule and non-violence.",
    link: QUIZ_WIKI("Hind_Swaraj") },
  { difficulty: "easy", q: "Which princely state's Nizam resisted joining India until a swift 1948 military action called Operation Polo?",
    options: ["Hyderabad", "Junagadh", "Kashmir", "Travancore"], correct: 0,
    explanation: "Hyderabad, the largest princely state, was integrated into India after Operation Polo, a five-day police action in September 1948.",
    link: QUIZ_WIKI("Indian_annexation_of_Hyderabad") },
  { difficulty: "easy", q: "Which Maratha ruler was crowned Chhatrapati at Raigad Fort in 1674, founding the Maratha Empire?",
    options: ["Shivaji", "Baji Rao I", "Sambhaji", "Tanaji Malusare"], correct: 0,
    explanation: "Shivaji's 1674 coronation at Raigad formally founded the Maratha Empire, the first major Indian power to directly resist Mughal authority.",
    link: QUIZ_WIKI("Shivaji") },
  { difficulty: "easy", q: "Who became independent India's first President, having earlier organised the Champaran Satyagraha with Gandhi?",
    options: ["Rajendra Prasad", "C. Rajagopalachari", "Sarvepalli Radhakrishnan", "Zakir Husain"], correct: 0,
    explanation: "Rajendra Prasad, a close associate of Gandhi during the Champaran movement, went on to become India's first President in 1950.",
    link: QUIZ_WIKI("Rajendra_Prasad") },
  { difficulty: "easy", q: "What is the name of India's Cellular Jail, used to imprison revolutionaries in solitary confinement?",
    options: ["Yerwada Jail", "Kala Pani", "Alfred Park", "Naini Central Jail"], correct: 1,
    explanation: "The Cellular Jail on the Andaman Islands, nicknamed 'Kala Pani' (black water), held hundreds of revolutionaries including Vinayak Damodar Savarkar.",
    link: QUIZ_WIKI("Cellular_Jail") },

  /* ---------------- MEDIUM (53) ---------------- */
  { difficulty: "medium", q: "What was the name of the mass campaign Gandhi launched in 1920, urging Indians to boycott British institutions?",
    options: ["Quit India Movement", "Non-Cooperation Movement", "Civil Disobedience Movement", "Khilafat Movement"], correct: 1,
    explanation: "The Non-Cooperation Movement was the first mass campaign of organised non-violent resistance.",
    link: QUIZ_WIKI("Non-cooperation_movement_(1919%E2%80%931922)") },
  { difficulty: "medium", q: "Which 1922 incident led Gandhi to call off the Non-Cooperation Movement?",
    options: ["The Chauri Chaura incident", "The Jallianwala Bagh massacre", "The Simon Commission protests", "The Champaran Satyagraha"], correct: 0,
    explanation: "After a mob killed 22 policemen at Chauri Chaura, Gandhi suspended the movement, insisting the means mattered as much as the end.",
    link: QUIZ_WIKI("Chauri_Chaura_incident") },
  { difficulty: "medium", q: "At which Congress session in 1929 was “Purna Swaraj” (complete independence) declared the goal?",
    options: ["The Bombay session", "The Lahore session", "The Calcutta session", "The Nagpur session"], correct: 1,
    explanation: "At its Lahore session in December 1929, Congress declared complete independence as its goal.",
    link: QUIZ_WIKI("Purna_Swaraj") },
  { difficulty: "medium", q: "Which two revolutionaries were hanged alongside Bhagat Singh on 23 March 1931?",
    options: ["Rajguru and Sukhdev", "Azad and Chaki", "Bismil and Ashfaqulla", "Rajguru and Azad"], correct: 0,
    explanation: "Bhagat Singh, Rajguru, and Sukhdev were executed together in Lahore on 23 March 1931.",
    link: QUIZ_WIKI("Execution_of_Bhagat_Singh,_Rajguru_and_Sukhdev") },
  { difficulty: "medium", q: "Who vowed never to be captured alive and died in a shootout at Allahabad's Alfred Park in 1931?",
    options: ["Chandrashekhar Azad", "Bhagat Singh", "Khudiram Bose", "Ram Prasad Bismil"], correct: 0,
    explanation: "Chandrashekhar Azad fought until his last bullet, then took his own life rather than surrender.",
    link: QUIZ_WIKI("Chandrashekhar_Azad") },
  { difficulty: "medium", q: "What organisation did Bhagat Singh and Chandrashekhar Azad belong to?",
    options: ["The Ghadar Party", "The Hindustan Socialist Republican Association", "The Anushilan Samiti", "The Indian Independence League"], correct: 1,
    explanation: "Both were key figures in the Hindustan Socialist Republican Association.",
    link: QUIZ_WIKI("Chandrashekhar_Azad") },
  { difficulty: "medium", q: "In which European city did Bhikaiji Cama unfurl an early version of India's flag in 1907?",
    options: ["Paris", "London", "Stuttgart", "Geneva"], correct: 2,
    explanation: "Cama unfurled her flag design at the International Socialist Congress in Stuttgart, Germany, on 22 August 1907.",
    link: QUIZ_WIKI("Bhikaiji_Cama") },
  { difficulty: "medium", q: "Who was the youngest Indian revolutionary executed by the British, hanged at just 18 in 1908?",
    options: ["Khudiram Bose", "Prafulla Chaki", "Bhagat Singh", "Ashfaqulla Khan"], correct: 0,
    explanation: "Khudiram Bose was hanged on 11 August 1908 at age 18 for a bombing attempt in Muzaffarpur.",
    link: QUIZ_WIKI("Khudiram_Bose") },
  { difficulty: "medium", q: "In which city did Khudiram Bose's bombing attempt take place?",
    options: ["Muzaffarpur", "Calcutta", "Patna", "Dhaka"], correct: 0,
    explanation: "Bose and Prafulla Chaki attempted to bomb a magistrate's carriage in Muzaffarpur in April 1908.",
    link: QUIZ_WIKI("Khudiram_Bose") },
  { difficulty: "medium", q: "Who co-founded the Home Rule League alongside Annie Besant in 1916?",
    options: ["Bal Gangadhar Tilak", "Gopal Krishna Gokhale", "Lala Lajpat Rai", "Bipin Chandra Pal"], correct: 0,
    explanation: "Tilak and Besant separately launched Home Rule Leagues in 1916, demanding self-government within the Empire.",
    link: QUIZ_WIKI("Bal_Gangadhar_Tilak") },
  { difficulty: "medium", q: "What was Bal Gangadhar Tilak's popular title, meaning “accepted by the people as their leader”?",
    options: ["Netaji", "Sardar", "Lokmanya", "Mahatma"], correct: 2,
    explanation: "Tilak was known as “Lokmanya” for his mass popular following.",
    link: QUIZ_WIKI("Bal_Gangadhar_Tilak") },
  { difficulty: "medium", q: "Which repressive 1919 law, allowing arrest without trial, provoked the protests that led to Jallianwala Bagh?",
    options: ["The Rowlatt Act", "The Salt Act", "The Vernacular Press Act", "The Ilbert Bill"], correct: 0,
    explanation: "The Rowlatt Act granted the British sweeping powers of arrest without trial, sparking nationwide protest.",
    link: QUIZ_WIKI("Jallianwala_Bagh_massacre") },
  { difficulty: "medium", q: "Who died from injuries sustained in a police lathi charge while protesting the Simon Commission in 1928?",
    options: ["Lala Lajpat Rai", "Bal Gangadhar Tilak", "Bipin Chandra Pal", "Gopal Krishna Gokhale"], correct: 0,
    explanation: "Lala Lajpat Rai died weeks after being struck during a protest march in Lahore in 1928.",
    link: QUIZ_WIKI("Lala_Lajpat_Rai") },
  { difficulty: "medium", q: "What was Lala Lajpat Rai's popular title?",
    options: ["Punjab Kesari", "Sher-e-Punjab", "Lokmanya", "Deshbandhu"], correct: 0,
    explanation: "Lajpat Rai was known as “Punjab Kesari” — the Lion of Punjab.",
    link: QUIZ_WIKI("Lala_Lajpat_Rai") },
  { difficulty: "medium", q: "Which commission, sent to India in 1928 to recommend constitutional reform, had no Indian members at all?",
    options: ["The Simon Commission", "The Cripps Mission", "The Cabinet Mission", "The Hunter Commission"], correct: 0,
    explanation: "The all-British Simon Commission's composition provoked widespread protest across India.",
    link: QUIZ_WIKI("Lala_Lajpat_Rai") },
  { difficulty: "medium", q: "In which year did Subhas Chandra Bose form the Provisional Government of Azad Hind?",
    options: ["1941", "1943", "1945", "1947"], correct: 1,
    explanation: "Bose formed the Provisional Government of Free India in Singapore in 1943.",
    link: QUIZ_WIKI("Subhas_Chandra_Bose") },
  { difficulty: "medium", q: "In which city did Bose form the Indian National Army's government-in-exile?",
    options: ["Tokyo", "Rangoon", "Singapore", "Berlin"], correct: 2,
    explanation: "The Provisional Government of Azad Hind was proclaimed in Japanese-occupied Singapore.",
    link: QUIZ_WIKI("Subhas_Chandra_Bose") },
  { difficulty: "medium", q: "Where were captured INA officers controversially tried for treason in 1945?",
    options: ["The Red Fort, Delhi", "Fort William, Calcutta", "Viceroy's House, Delhi", "Government House, Lahore"], correct: 0,
    explanation: "The INA trials at the Red Fort united Indians of many political stripes in protest.",
    link: QUIZ_WIKI("Indian_National_Army_trials") },
  { difficulty: "medium", q: "In which Indian city did the Royal Indian Navy mutiny begin in February 1946?",
    options: ["Calcutta", "Bombay", "Madras", "Karachi"], correct: 1,
    explanation: "The mutiny began among naval ratings in Bombay before spreading across British India.",
    link: QUIZ_WIKI("Royal_Indian_Navy_mutiny") },
  { difficulty: "medium", q: "Roughly how many princely states did Sardar Patel help integrate into the Indian Union after independence?",
    options: ["Around 100", "Over 250", "Over 560", "Nearly 1,000"], correct: 2,
    explanation: "Patel's political integration effort brought over 560 princely states into the Indian Union.",
    link: QUIZ_WIKI("Vallabhbhai_Patel") },
  { difficulty: "medium", q: "Who became the youngest-ever President of the Indian National Congress in 1923, at the age of 35?",
    options: ["Maulana Abul Kalam Azad", "Jawaharlal Nehru", "Subhas Chandra Bose", "Motilal Nehru"], correct: 0,
    explanation: "Maulana Azad, a scholar of Islamic theology, became Congress President in 1923.",
    link: QUIZ_WIKI("Abul_Kalam_Azad") },
  { difficulty: "medium", q: "Who served as independent India's first Minister of Education?",
    options: ["Maulana Abul Kalam Azad", "Sarojini Naidu", "Rajendra Prasad", "C. Rajagopalachari"], correct: 0,
    explanation: "Maulana Azad laid the foundations of India's university and school systems as its first Education Minister.",
    link: QUIZ_WIKI("Abul_Kalam_Azad") },
  { difficulty: "medium", q: "Which Viceroy oversaw Britain's transfer of power to India in 1947?",
    options: ["Lord Wavell", "Lord Mountbatten", "Lord Curzon", "Lord Linlithgow"], correct: 1,
    explanation: "Lord Mountbatten was Britain's last Viceroy of India, overseeing independence and Partition.",
    link: QUIZ_WIKI("Indian_Independence_Day") },
  { difficulty: "medium", q: "What is the name given to the boundary line that divided India and Pakistan?",
    options: ["The Durand Line", "The McMahon Line", "The Radcliffe Line", "The Curzon Line"], correct: 2,
    explanation: "The Radcliffe Line, drawn by Sir Cyril Radcliffe, demarcated the boundary through Punjab and Bengal.",
    link: QUIZ_WIKI("Radcliffe_Line") },
  { difficulty: "medium", q: "Which British lawyer was tasked with drawing the boundary between India and Pakistan?",
    options: ["Sir Cyril Radcliffe", "Sir Stafford Cripps", "Lord Pethick-Lawrence", "Sir Reginald Coupland"], correct: 0,
    explanation: "Cyril Radcliffe chaired the boundary commissions for Punjab and Bengal despite never having visited India before.",
    link: QUIZ_WIKI("Radcliffe_Line") },
  { difficulty: "medium", q: "In which Bombay park did Gandhi deliver his “Do or Die” Quit India speech?",
    options: ["Gowalia Tank Maidan", "Shivaji Park", "Azad Maidan", "Chowpatty Beach"], correct: 0,
    explanation: "Gandhi launched the Quit India Movement at Gowalia Tank Maidan on 8 August 1942.",
    link: QUIZ_WIKI("Quit_India_Movement") },
  { difficulty: "medium", q: "On what date was the Quit India Resolution passed?",
    options: ["8 August 1942", "15 August 1942", "26 January 1942", "9 August 1942"], correct: 0,
    explanation: "Congress passed the Quit India Resolution on 8 August 1942, triggering mass arrests overnight.",
    link: QUIZ_WIKI("Quit_India_Movement") },
  { difficulty: "medium", q: "On what date did the Constitution of India come into effect?",
    options: ["15 August 1947", "26 November 1949", "26 January 1950", "2 October 1950"], correct: 2,
    explanation: "The Constitution, adopted in November 1949, came into effect on 26 January 1950 — now celebrated as Republic Day.",
    link: QUIZ_WIKI("Constitution_of_India") },
  { difficulty: "medium", q: "Which act of the British Parliament, given royal assent on 18 July 1947, formally created the independent dominions of India and Pakistan?",
    options: ["The Government of India Act 1935", "The Indian Independence Act 1947", "The Rowlatt Act", "The Indian Councils Act"], correct: 1,
    explanation: "The Indian Independence Act 1947 received royal assent weeks before India actually became independent.",
    link: QUIZ_WIKI("Indian_Independence_Act_1947") },
  { difficulty: "medium", q: "Which act transferred control of India from the East India Company to the British Crown in 1858?",
    options: ["The Regulating Act", "The Government of India Act 1858", "The Pitt's India Act", "The Charter Act"], correct: 1,
    explanation: "Following the 1857 uprising, this act dissolved the Company and passed India directly to the Crown.",
    link: QUIZ_WIKI("Government_of_India_Act_1858") },
  { difficulty: "medium", q: "Which act of 1935 introduced provincial autonomy in British India?",
    options: ["The Government of India Act 1935", "The Indian Councils Act 1909", "The Rowlatt Act", "The Simon Report"], correct: 0,
    explanation: "The Government of India Act 1935 granted limited provincial self-government while keeping ultimate power in British hands.",
    link: QUIZ_WIKI("Government_of_India_Act_1935") },
  { difficulty: "medium", q: "Which mission, arriving in India in March 1946, proposed a plan for transferring power?",
    options: ["The Cripps Mission", "The Cabinet Mission", "The Simon Commission", "The Stafford Mission"], correct: 1,
    explanation: "Three British Cabinet ministers formed the 1946 Cabinet Mission to discuss the transfer of power.",
    link: QUIZ_WIKI("1946_Cabinet_Mission_to_India") },
  { difficulty: "medium", q: "What is the name for the widespread communal violence that broke out in Calcutta on 16 August 1946?",
    options: ["The Noakhali riots", "Direct Action Day", "The Great Rebellion", "Black Friday"], correct: 1,
    explanation: "Direct Action Day, called by the Muslim League, led to days of rioting in Calcutta with thousands killed.",
    link: QUIZ_WIKI("Direct_Action_Day") },
  { difficulty: "medium", q: "Who succeeded Lord Mountbatten as Governor-General of India in 1948?",
    options: ["Rajendra Prasad", "C. Rajagopalachari", "Sardar Patel", "Jawaharlal Nehru"], correct: 1,
    explanation: "C. Rajagopalachari became independent India's only Indian-born Governor-General, serving until 1950.",
    link: QUIZ_WIKI("C._Rajagopalachari") },
  { difficulty: "medium", q: "What title, meaning “Great Leader”, was given to Muhammad Ali Jinnah?",
    options: ["Quaid-i-Azam", "Sardar", "Netaji", "Maulana"], correct: 0,
    explanation: "Jinnah, who led the campaign for Pakistan, was known as “Quaid-i-Azam”.",
    link: QUIZ_WIKI("Muhammad_Ali_Jinnah") },

    { difficulty: "medium", q: "Which 1764 battle gave the East India Company the right to collect revenue (Diwani) across Bengal, Bihar, and Odisha?",
    options: ["Battle of Plassey", "Battle of Buxar", "Battle of Wandiwash", "Battle of Assaye"], correct: 1,
    explanation: "Victory at the Battle of Buxar in 1764 won the Company the Diwani rights, transforming it from a trading firm into a revenue-collecting power.",
    link: QUIZ_WIKI("Battle_of_Buxar") },
  { difficulty: "medium", q: "Which 1806 sepoy uprising against new East India Company dress regulations predates 1857 as the first large-scale mutiny against Company rule?",
    options: ["Vellore Mutiny", "Barrackpore Mutiny of 1824", "Meerut Mutiny", "Ghadar Mutiny"], correct: 0,
    explanation: "The Vellore Mutiny of 1806, sparked partly by dress rules seen as an affront to soldiers' faith, was the first large-scale armed mutiny against the Company, half a century before 1857.",
    link: QUIZ_WIKI("Vellore_mutiny") },
  { difficulty: "medium", q: "Which Maharaja of Jammu and Kashmir signed the Instrument of Accession, joining the state to India in October 1947?",
    options: ["Hari Singh", "Ranjit Singh", "Gulab Singh", "Pratap Singh"], correct: 0,
    explanation: "Maharaja Hari Singh signed the Instrument of Accession as raiders backed by Pakistan advanced on Srinagar.",
    link: QUIZ_WIKI("Hari_Singh") },
  { difficulty: "medium", q: "Which Gujarat princely state's Muslim ruler acceded to Pakistan in 1947 despite a Hindu-majority population, before a plebiscite favoured India?",
    options: ["Junagadh", "Bhavnagar", "Baroda", "Kutch"], correct: 0,
    explanation: "Junagadh's ruler acceded to Pakistan despite having no shared border with it; India intervened, and a plebiscite overwhelmingly favoured joining India.",
    link: QUIZ_WIKI("Junagadh_State") },
  { difficulty: "medium", q: "Who led the 1930 Chittagong Armoury Raid, briefly declaring a provisional independent government?",
    options: ["Surya Sen", "Pritilata Waddedar", "Rash Behari Bose", "Jatindranath Das"], correct: 0,
    explanation: "Surya Sen led dozens of young revolutionaries in a coordinated raid on Chittagong's armouries in April 1930.",
    link: QUIZ_WIKI("Chittagong_armoury_raid") },
  { difficulty: "medium", q: "Which young revolutionary took her own life rather than be captured after leading an armed raid on a whites-only club in Chittagong in 1932?",
    options: ["Pritilata Waddedar", "Kalpana Dutt", "Bina Das", "Kamala Nehru"], correct: 0,
    explanation: "Pritilata Waddedar led a raid on the Pahartali European Club and, surrounded by police, took cyanide rather than be captured.",
    link: QUIZ_WIKI("Pritilata_Waddedar") },
  { difficulty: "medium", q: "Who assassinated Nashik's district collector in 1909 and was hanged at just 19?",
    options: ["Anant Laxman Kanhere", "Khudiram Bose", "Madan Lal Dhingra", "Kanhaiyalal Dutt"], correct: 0,
    explanation: "Anant Laxman Kanhere shot district collector A. M. T. Jackson at a Nashik theatre in December 1909, and was hanged the following year.",
    link: QUIZ_WIKI("Anant_Laxman_Kanhere") },
  { difficulty: "medium", q: "Who was elected Congress president at the 1938 Haripura session, presiding over a pageant designed by artist Nandalal Bose?",
    options: ["Subhas Chandra Bose", "Jawaharlal Nehru", "Maulana Azad", "Rajendra Prasad"], correct: 0,
    explanation: "Subhas Chandra Bose was elected Congress president at Haripura in 1938; his push for a tougher anti-British line would split the party within a year.",
    link: QUIZ_WIKI("Subhas_Chandra_Bose") },
  { difficulty: "medium", q: "Who founded the Ghadar Party among Indian immigrants in North America to organise armed revolution against British rule?",
    options: ["Lala Har Dayal", "Vinayak Damodar Savarkar", "Ras Bihari Bose", "Shyamji Krishna Varma"], correct: 0,
    explanation: "Lala Har Dayal founded the Ghadar Party in San Francisco in 1913, aiming to spark an armed mutiny within the Indian Army.",
    link: QUIZ_WIKI("Har_Dayal") },
  { difficulty: "medium", q: "Whose 1905 decision to partition Bengal along religious lines ignited the Swadeshi movement and mass boycotts of British goods?",
    options: ["Lord Curzon", "Lord Lytton", "Lord Dalhousie", "Lord Minto"], correct: 0,
    explanation: "Viceroy Lord Curzon's partition of Bengal was meant to weaken nationalist sentiment; it instead sparked the Swadeshi boycott movement.",
    link: QUIZ_WIKI("Partition_of_Bengal_(1905)") },
  { difficulty: "medium", q: "Which campaign saw volunteers court arrest across Nagpur in 1923 for the simple act of publicly carrying the nationalist tricolour?",
    options: ["Flag Satyagraha", "Vaikom Satyagraha", "Individual Satyagraha", "Salt Satyagraha"], correct: 0,
    explanation: "The 1923 Nagpur Flag Satyagraha established the nationalist tricolour as a defiant symbol of the freedom struggle.",
    link: QUIZ_WIKI("Flag_Satyagraha") },
  { difficulty: "medium", q: "Who was given the title 'Rani' by Jawaharlal Nehru for leading a Naga uprising against British rule at the age of just 16?",
    options: ["Rani Gaidinliu", "Rani Lakshmibai", "Begum Hazrat Mahal", "Chand Bibi"], correct: 0,
    explanation: "Rani Gaidinliu led a 1932 uprising in the northeast and was imprisoned for 14 years; Nehru later honoured her with the title 'Rani'.",
    link: QUIZ_WIKI("Rani_Gaidinliu") },
  { difficulty: "medium", q: "Which 1818 battle, in which soldiers from the long-excluded Mahar caste fought for the Company, effectively ended Maratha power?",
    options: ["Battle of Koregaon", "Battle of Kirkee", "Battle of Ashti", "Battle of Sitabaldi"], correct: 0,
    explanation: "The Battle of Koregaon is still commemorated every January by Dalit communities as a symbol of resistance to caste oppression.",
    link: QUIZ_WIKI("Battle_of_Koregaon") },
  { difficulty: "medium", q: "Which parallel salt march, led by C. Rajagopalachari in 1930, ran from Tiruchirapalli to Vedaranyam on the Tamil coast?",
    options: ["Dharasana Satyagraha", "Vedaranyam Salt March", "Dandi March", "Kheda Satyagraha"], correct: 1,
    explanation: "Rajagopalachari led a parallel salt march in the south just as Gandhi marched to Dandi in the west.",
    link: QUIZ_WIKI("C._Rajagopalachari") },
  { difficulty: "medium", q: "What was the outcome for Kasturba Gandhi, who was detained alongside her husband at the Aga Khan Palace in Poona after Quit India was launched?",
    options: ["She was released within weeks", "She died in detention in 1944", "She escaped detention", "She was exiled abroad"], correct: 1,
    explanation: "Kasturba Gandhi died at the Aga Khan Palace in 1944 after 18 months of imprisonment, one of the movement's final personal costs before independence.",
    link: QUIZ_WIKI("Aga_Khan_Palace") },
  { difficulty: "medium", q: "At which Manipur village did the Indian National Army first raise the tricolour on Indian soil in 1944?",
    options: ["Imphal", "Kohima", "Moirang", "Dimapur"], correct: 2,
    explanation: "Bose's INA, advancing alongside Japanese forces, raised the Indian flag at Moirang — briefly, a patch of Indian soil free of British rule.",
    link: QUIZ_WIKI("Moirang") },
  { difficulty: "medium", q: "Which battle, fought alongside Kohima in 1944, broke Japan's invasion of India and turned the tide of the Burma campaign?",
    options: ["Battle of Imphal", "Battle of Meiktila", "Battle of Sittang Bend", "Battle of Mandalay"], correct: 0,
    explanation: "The twin battles of Kohima and Imphal stopped Japan's advance into India and marked the turning point of the Burma campaign.",
    link: QUIZ_WIKI("Battle_of_Imphal") },
  { difficulty: "medium", q: "Which East India Company official led the assault that defeated Tipu Sultan at Seringapatam in 1799?",
    options: ["Lord Wellesley", "Lord Cornwallis", "Arthur Wellesley", "Lord Clive"], correct: 0,
    explanation: "Governor-General Lord Wellesley directed the campaign that ended in the storming of Seringapatam and Tipu Sultan's death in 1799.",
    link: QUIZ_WIKI("Siege_of_Seringapatam_(1799)") },

  /* ---------------- HARD (45) ---------------- */
  { difficulty: "hard", q: "What was Rani Lakshmibai's birth name before her marriage?",
    options: ["Manikarnika Tambe", "Lakshmi Bai Newalkar", "Kashi Bai", "Jhalkari Bai"], correct: 0,
    explanation: "Born Manikarnika Tambe in Varanasi, she took the name Lakshmibai on becoming Queen of Jhansi.",
    link: QUIZ_WIKI("Rani_of_Jhansi") },
  { difficulty: "hard", q: "In which 1757 battle did the East India Company defeat the Nawab of Bengal to establish political control?",
    options: ["The Battle of Buxar", "The Battle of Plassey", "The Battle of Wandiwash", "The Battle of Panipat"], correct: 1,
    explanation: "Victory at Plassey marked the moment the Company stopped trading and started ruling.",
    link: QUIZ_WIKI("Battle_of_Plassey") },
  { difficulty: "hard", q: "Which Nawab of Bengal was defeated at the Battle of Plassey?",
    options: ["Siraj-ud-Daulah", "Mir Jafar", "Shuja-ud-Daulah", "Alivardi Khan"], correct: 0,
    explanation: "Siraj-ud-Daulah's defeat at Plassey opened the door to Company rule in Bengal.",
    link: QUIZ_WIKI("Battle_of_Plassey") },
  { difficulty: "hard", q: "Who commanded the East India Company's forces at the Battle of Plassey?",
    options: ["Robert Clive", "Warren Hastings", "Arthur Wellesley", "Charles Cornwallis"], correct: 0,
    explanation: "Robert Clive led the Company's forces to victory at Plassey, aided by the defection of Mir Jafar.",
    link: QUIZ_WIKI("Battle_of_Plassey") },
  { difficulty: "hard", q: "What British colonial policy allowed annexation of princely states without a natural male heir, used to annex Jhansi?",
    options: ["The Subsidiary Alliance", "The Doctrine of Lapse", "The Permanent Settlement", "The Ryotwari System"], correct: 1,
    explanation: "The Doctrine of Lapse let the British annex Jhansi after refusing to recognise Rani Lakshmibai's adopted son as heir.",
    link: QUIZ_WIKI("Doctrine_of_Lapse") },
  { difficulty: "hard", q: "Who accompanied Khudiram Bose in the Muzaffarpur bombing attempt and took his own life rather than be captured?",
    options: ["Prafulla Chaki", "Kanailal Dutt", "Satyendranath Bose", "Barindra Ghosh"], correct: 0,
    explanation: "Prafulla Chaki shot himself when surrounded by police rather than be taken alive.",
    link: QUIZ_WIKI("Khudiram_Bose") },
  { difficulty: "hard", q: "Alongside Tilak and Lajpat Rai, who was the third leader of the “Lal-Bal-Pal” nationalist trio?",
    options: ["Bipin Chandra Pal", "Gopal Krishna Gokhale", "Aurobindo Ghosh", "Surendranath Banerjee"], correct: 0,
    explanation: "Lal (Lajpat Rai), Bal (Tilak), and Pal (Bipin Chandra Pal) pushed the Congress toward more assertive nationalism.",
    link: QUIZ_WIKI("Lala_Lajpat_Rai") },
  { difficulty: "hard", q: "From which two universities did Dr. B. R. Ambedkar earn doctorates?",
    options: ["Oxford and Cambridge", "Columbia University and the London School of Economics", "Harvard and Yale", "Columbia and Oxford"], correct: 1,
    explanation: "Ambedkar earned doctorates from Columbia University in the US and the LSE in London.",
    link: QUIZ_WIKI("B._R._Ambedkar") },
  { difficulty: "hard", q: "Which magistrate, notorious for harsh sentences against nationalists, was the intended target of the Muzaffarpur bombing?",
    options: ["Douglas Kingsford", "Michael O'Dwyer", "Reginald Dyer", "James Peddie"], correct: 0,
    explanation: "Khudiram Bose and Prafulla Chaki targeted magistrate Douglas Kingsford's carriage, but killed two British women instead.",
    link: QUIZ_WIKI("Khudiram_Bose") },
  { difficulty: "hard", q: "In which legislative building did Bhagat Singh and Batukeshwar Dutt throw a bomb in 1929 to protest repressive laws?",
    options: ["The Central Legislative Assembly, Delhi", "The Punjab Legislative Council, Lahore", "The Imperial Legislative Council, Calcutta", "Viceroy's House, Delhi"], correct: 0,
    explanation: "The two threw non-lethal bombs into the Assembly, then courted arrest to use their trial as a public platform.",
    link: QUIZ_WIKI("Bhagat_Singh") },
  { difficulty: "hard", q: "How many ships and shore establishments were ultimately involved in the 1946 Royal Indian Navy mutiny?",
    options: ["About 10", "About 25", "More than 56", "Over 100"], correct: 2,
    explanation: "The mutiny grew to involve over 10,000 sailors across more than 56 ships and shore establishments.",
    link: QUIZ_WIKI("Royal_Indian_Navy_mutiny") },
  { difficulty: "hard", q: "On what date was the Radcliffe Line — the actual India-Pakistan boundary — officially announced, two days after independence?",
    options: ["15 August 1947", "17 August 1947", "20 August 1947", "3 June 1947"], correct: 1,
    explanation: "The boundary was announced on 17 August 1947, meaning the new nations began without knowing their exact borders.",
    link: QUIZ_WIKI("Radcliffe_Line") },
  { difficulty: "hard", q: "Which three British Cabinet ministers made up the 1946 Cabinet Mission?",
    options: ["Attlee, Wavell, and Cripps", "Pethick-Lawrence, Cripps, and Alexander", "Mountbatten, Cripps, and Linlithgow", "Pethick-Lawrence, Attlee, and Alexander"], correct: 1,
    explanation: "Lord Pethick-Lawrence, Sir Stafford Cripps, and A. V. Alexander formed the Cabinet Mission.",
    link: QUIZ_WIKI("1946_Cabinet_Mission_to_India") },
  { difficulty: "hard", q: "Who was Prime Minister of Britain when the Cabinet Mission was sent to India in 1946?",
    options: ["Winston Churchill", "Clement Attlee", "Neville Chamberlain", "Stanley Baldwin"], correct: 1,
    explanation: "Clement Attlee's Labour government initiated the Cabinet Mission and later oversaw India's independence.",
    link: QUIZ_WIKI("1946_Cabinet_Mission_to_India") },
  { difficulty: "hard", q: "Approximately how many people were killed in the Direct Action Day violence in Calcutta in August 1946?",
    options: ["Several hundred", "Several thousand (4,000–10,000)", "Around 50,000", "Fewer than 100"], correct: 1,
    explanation: "Estimates of the dead in the Great Calcutta Killings range from roughly 4,000 to 10,000.",
    link: QUIZ_WIKI("Direct_Action_Day") },
  { difficulty: "hard", q: "In which city did Rani Lakshmibai die fighting in 1858?",
    options: ["Jhansi", "Gwalior", "Kanpur", "Lucknow"], correct: 1,
    explanation: "She died in battle at Gwalior on 18 June 1858, sword in hand by most accounts.",
    link: QUIZ_WIKI("Rani_of_Jhansi") },
  { difficulty: "hard", q: "Which international gathering did Bhikaiji Cama address when she unfurled her flag design in 1907?",
    options: ["The International Socialist Congress", "The League of Nations Assembly", "The Pan-Asian Conference", "The Round Table Conference"], correct: 0,
    explanation: "Cama addressed the International Socialist Congress in Stuttgart, declaring her flag that of India's independence.",
    link: QUIZ_WIKI("Bhikaiji_Cama") },
  { difficulty: "hard", q: "What was the immediate outcome of the Chauri Chaura incident in 1922?",
    options: ["A mob killed 22 policemen after setting fire to a police station", "British troops fired on protesters", "A courthouse was burned down", "Congress leaders were arrested en masse"], correct: 0,
    explanation: "Protesters set fire to a police station, killing 22 policemen inside — prompting Gandhi to suspend the movement.",
    link: QUIZ_WIKI("Chauri_Chaura_incident") },
  { difficulty: "hard", q: "Who preceded C. Rajagopalachari as Governor-General of independent India?",
    options: ["Lord Wavell", "Lord Mountbatten", "Lord Linlithgow", "Lord Willingdon"], correct: 1,
    explanation: "Mountbatten served as independent India's first Governor-General before Rajagopalachari succeeded him in 1948.",
    link: QUIZ_WIKI("C._Rajagopalachari") },
  { difficulty: "hard", q: "Which position did C. Rajagopalachari hold immediately after independence, before becoming Governor-General?",
    options: ["Governor of West Bengal", "Governor of Madras", "Home Minister", "Chief Justice of India"], correct: 0,
    explanation: "Rajagopalachari served as Governor of West Bengal from August 1947 before becoming Governor-General in 1948.",
    link: QUIZ_WIKI("C._Rajagopalachari") },
  { difficulty: "hard", q: "In what year did Bal Gangadhar Tilak die?",
    options: ["1915", "1920", "1925", "1930"], correct: 1,
    explanation: "Tilak died in 1920, remaining a defining voice of the movement's early, uncompromising wing until the end.",
    link: QUIZ_WIKI("Bal_Gangadhar_Tilak") },
  { difficulty: "hard", q: "For how many years was Bal Gangadhar Tilak imprisoned in Mandalay for sedition?",
    options: ["Two years", "Four years", "Six years", "Ten years"], correct: 2,
    explanation: "Tilak served a six-year sedition sentence in Mandalay, Burma.",
    link: QUIZ_WIKI("Bal_Gangadhar_Tilak") },
  { difficulty: "hard", q: "Sardar Vallabhbhai Patel organised peasant satyagrahas in which two Gujarat regions that earned him the title “Sardar”?",
    options: ["Kheda and Bardoli", "Surat and Baroda", "Ahmedabad and Rajkot", "Kutch and Saurashtra"], correct: 0,
    explanation: "His leadership of the Kheda and Bardoli satyagrahas earned Patel the title “Sardar”, meaning chief.",
    link: QUIZ_WIKI("Vallabhbhai_Patel") },
  { difficulty: "hard", q: "By what unusual mode of transport did Subhas Chandra Bose travel from Germany to Southeast Asia in 1943?",
    options: ["By submarine", "By flying boat", "By overland caravan", "By hospital ship"], correct: 0,
    explanation: "Bose transferred from a German U-boat to a Japanese submarine at sea, one of the most audacious journeys of the era.",
    link: QUIZ_WIKI("Subhas_Chandra_Bose") },
  { difficulty: "hard", q: "What academic/professional exam did Subhas Chandra Bose pass in England before resigning it to join the freedom movement?",
    options: ["The Bar examination", "The Indian Civil Service exam", "The Royal Society fellowship", "The Cambridge Tripos"], correct: 1,
    explanation: "Bose cleared the Indian Civil Service exam in England, then resigned it to join the independence movement.",
    link: QUIZ_WIKI("Subhas_Chandra_Bose") },
  { difficulty: "hard", q: "What year did the Royal Indian Navy mutiny take place?",
    options: ["1942", "1944", "1946", "1948"], correct: 2,
    explanation: "The mutiny broke out in February 1946, signalling that the empire could no longer rely on its own forces.",
    link: QUIZ_WIKI("Royal_Indian_Navy_mutiny") },
  { difficulty: "hard", q: "On what date did the Indian Independence Act 1947 receive royal assent, weeks before India actually became independent?",
    options: ["3 June 1947", "18 July 1947", "1 August 1947", "14 August 1947"], correct: 1,
    explanation: "The Act received royal assent on 18 July 1947, with independence itself commencing on 15 August.",
    link: QUIZ_WIKI("Indian_Independence_Act_1947") },
  { difficulty: "hard", q: "Approximately how many people are estimated to have been displaced during the Partition of India, the largest mass migration in history?",
    options: ["Around 1 million", "Around 5 million", "Around 10–15 million", "Around 30 million"], correct: 2,
    explanation: "Some ten to fifteen million people crossed the new India-Pakistan border in both directions.",
    link: QUIZ_WIKI("Partition_of_India") },
  { difficulty: "hard", q: "Besides India, which two present-day nations trace their borders in part to the Radcliffe Line?",
    options: ["Pakistan and Bangladesh", "Pakistan and Nepal", "Nepal and Bhutan", "Pakistan and Myanmar"], correct: 0,
    explanation: "The Radcliffe Line's Punjab and Bengal boundaries continue to define parts of India's borders with Pakistan and Bangladesh.",
    link: QUIZ_WIKI("Radcliffe_Line") },
  { difficulty: "hard", q: "At what age was Khudiram Bose hanged, making him the youngest revolutionary executed by the British?",
    options: ["16", "18", "20", "22"], correct: 1,
    explanation: "Khudiram Bose was hanged on 11 August 1908 at age 18.",
    link: QUIZ_WIKI("Khudiram_Bose") },  { difficulty: "hard", q: "Which East India Company captain commanded the Hector, the first Company ship to reach Surat in 1608?",
    options: ["William Hawkins", "Thomas Best", "Robert Clive", "Job Charnock"], correct: 0,
    explanation: "Sir William Hawkins commanded the Hector, anchoring at Surat on 24 August 1608 to seek trading rights from Jahangir's court.",
    link: QUIZ_WIKI("William_Hawkins_(fl._c._1600)") },
  { difficulty: "hard", q: "Which 1612 naval battle near Surat, an English victory over a Portuguese fleet, secured the East India Company's early trading position?",
    options: ["Battle of Swally", "Battle of Bombay Harbour", "Battle of Diu", "Battle of Chaul"], correct: 0,
    explanation: "The Battle of Swally saw four English East India Company ships defeat a larger Portuguese force off Surat's coast in 1612.",
    link: QUIZ_WIKI("Battle_of_Swally") },
  { difficulty: "hard", q: "Which Gurkha commander held the fort at Nalapani for over a month against a much larger British force in 1814, impressing the British into later recruiting Gurkha regiments?",
    options: ["Balbhadra Kunwar", "Amar Singh Thapa", "Bhakti Thapa", "Ranjur Singh Thapa"], correct: 0,
    explanation: "Balbhadra Kunwar's defence of Nalapani in the opening battle of the Anglo-Nepalese War became legendary on both sides.",
    link: QUIZ_WIKI("Battle_of_Nalapani") },
  { difficulty: "hard", q: "Who presided over the special Congress session in Calcutta in September 1920 that first adopted Gandhi's Non-Cooperation programme?",
    options: ["Lala Lajpat Rai", "Chittaranjan Das", "Motilal Nehru", "Bipin Chandra Pal"], correct: 0,
    explanation: "Lala Lajpat Rai chaired the September 1920 special session in Calcutta, months before the regular Nagpur session made Non-Cooperation official party policy.",
    link: QUIZ_WIKI("Non-cooperation_movement_(1919%E2%80%931922)") },
  { difficulty: "hard", q: "Which revolutionary organisation, responsible for the 1925 Kakori train robbery, did Ram Prasad Bismil and Ashfaqulla Khan belong to?",
    options: ["Hindustan Republican Association", "Anushilan Samiti", "Ghadar Party", "Abhinav Bharat Society"], correct: 0,
    explanation: "Bismil and Ashfaqulla Khan were leading members of the Hindustan Republican Association, which later reorganised as the Hindustan Socialist Republican Association.",
    link: QUIZ_WIKI("Kakori_conspiracy") },
  { difficulty: "hard", q: "In the 1760 Battle of Wandiwash, which British commander decisively defeated the French general Lally, ending French ambitions in India?",
    options: ["Eyre Coote", "Robert Clive", "Arthur Wellesley", "Charles Cornwallis"], correct: 0,
    explanation: "Eyre Coote's victory at Wandiwash broke French military power in India and decided the long Anglo-French contest in Britain's favour.",
    link: QUIZ_WIKI("Battle_of_Wandiwash") },
  { difficulty: "hard", q: "Which newspaper did Bal Gangadhar Tilak edit, using its fiery editorials to fuel two separate sedition trials against him?",
    options: ["Kesari", "The Hindu", "Amrita Bazar Patrika", "Young India"], correct: 0,
    explanation: "Tilak's Marathi-language newspaper Kesari carried the editorials that led to his 1897 and 1908 sedition trials.",
    link: QUIZ_WIKI("Bal_Gangadhar_Tilak") },
  { difficulty: "hard", q: "Which British Governor-General's tenure introduced the Doctrine of Lapse, used to annex princely states lacking a natural male heir?",
    options: ["Lord Dalhousie", "Lord Curzon", "Lord Canning", "Lord Bentinck"], correct: 0,
    explanation: "Lord Dalhousie's Doctrine of Lapse, applied between 1848 and 1856, allowed the Company to annex states such as Jhansi and Satara.",
    link: QUIZ_WIKI("Doctrine_of_lapse") },
  { difficulty: "hard", q: "Who led the Dharasana Satyagraha in 1930 after Gandhi's arrest, as volunteers were beaten while raiding a government salt works without resistance?",
    options: ["Sarojini Naidu", "Kasturba Gandhi", "Kamaladevi Chattopadhyay", "Aruna Asaf Ali"], correct: 0,
    explanation: "Sarojini Naidu led hundreds of volunteers on the Dharasana salt works; American journalist Webb Miller's eyewitness account turned world opinion against British rule.",
    link: QUIZ_WIKI("Dharasana_Satyagraha") },
  { difficulty: "hard", q: "Which Congress president resigned in 1939 after a dispute with Gandhi at the Tripuri session, later going on to found the Indian National Army?",
    options: ["Subhas Chandra Bose", "Acharya Kripalani", "Rajendra Prasad", "Abul Kalam Azad"], correct: 0,
    explanation: "Bose's re-election as Congress president in 1939 over Gandhi's preferred candidate led to a bitter split; he resigned within months.",
    link: QUIZ_WIKI("Subhas_Chandra_Bose") },
  { difficulty: "hard", q: "Which East India Company war, fought over Bombay-area ports against Aurangzeb's forces in 1686–90, ended in a humbled Company begging its way back into Mughal favour?",
    options: ["The Company's War with the Mughals", "The First Anglo-Maratha War", "The Carnatic Wars", "The Anglo-Sikh War"], correct: 0,
    explanation: "Company forces were crushed by Aurangzeb's navy in this 1686–90 conflict, a rare early setback that forced the Company to sue for peace.",
    link: QUIZ_WIKI("Anglo-Mughal_War_(1686%E2%80%931690)") },
  { difficulty: "hard", q: "Which 1848 siege, triggered by a local governor's revolt against the Sikh regency, reignited war between the British and the Sikh Empire?",
    options: ["Siege of Multan", "Siege of Lahore", "Siege of Amritsar", "Siege of Peshawar"], correct: 0,
    explanation: "The Siege of Multan escalated into the Second Anglo-Sikh War, which ended with the British annexation of Punjab.",
    link: QUIZ_WIKI("Siege_of_Multan") },
  { difficulty: "hard", q: "Which 1805 siege saw a British assault on a fortress-state fail after repeated attempts, leaving it independent for four more decades?",
    options: ["Siege of Bharatpur", "Siege of Gwalior", "Siege of Multan", "Siege of Seringapatam"], correct: 0,
    explanation: "The 1805 Siege of Bharatpur ended in a rare British failure — the fortress held out and remained independent until 1826.",
    link: QUIZ_WIKI("Siege_of_Bharatpur_(1805)") },
  { difficulty: "hard", q: "Which 1806 uprising was partly sparked by new East India Company regulations requiring sepoys to wear a leather cockade seen as religiously offensive?",
    options: ["Vellore Mutiny", "Barrackpore Mutiny", "Meerut Mutiny", "Anglo-Manipur War"], correct: 0,
    explanation: "New turban and cockade regulations at Vellore in 1806 were seen by sepoys as an attack on their faith, triggering the mutiny.",
    link: QUIZ_WIKI("Vellore_mutiny") },
  { difficulty: "hard", q: "Who commanded the tiny Company force, including soldiers from the long-marginalised Mahar caste, that held off a much larger Peshwa army at Koregaon in 1818?",
    options: ["Captain Francis Staunton", "Arthur Wellesley", "Charles Cornwallis", "Lord Lake"], correct: 0,
    explanation: "Captain Francis Staunton led the outnumbered force at the Battle of Koregaon, still commemorated by Dalit communities today.",
    link: QUIZ_WIKI("Battle_of_Koregaon") },
];
